### PR TITLE
Fix Sonoff 4CH Pro R2 - sensors and triggers

### PR DESCRIPTION
**Pull request by h0jeZvgoxFepBQ2C**
Doesn't work anymore under key "sensor", but with "binary_sensor".
Also included missing trigger, to make the buttons work on the device itself.

### CODE REVIEW

**Comment by jonathanadams** [comment]
@h0jeZvgoxFepBQ2C will you have a look at your labelling.

Can you also split out the optional configs into different code blocks (so a user can literally copy and paste the main block and it will work?)

**Comment by kamcio2603** [comment]
Hi, i tested your config,  please change GPI010 to GPIO10 (cannot resolve pin name GPI010), second - button R2 not working correctly (no actions /no logs)

**Review by h0jeZvgoxFepBQ2C — COMMENTED** [review]
Hope I fixed everything as you wished?

**Comment by jonathanadams** [comment]
@h0jeZvgoxFepBQ2C looks good. thanks for making the amendments.

**Pull request merged**
