### PR TITLE
Add Kogan Smart plug

### PR DESCRIPTION
**Pull request by sparkydave1981**
Add Kogan Smart Plug with Energy Monitoring to AU device list

### CODE REVIEW

**Comment by jonathanadams** [comment]
@sparkydave1981 Thanks for your contrubuton. 

Had to make a few slight corrections to formatting but now merged into project.

**Comment by sparkydave1981** [comment]
Sorry about the errors you had to fix, it was my first PR and just learning the process.  Hopefully I can use the notes from your changes to help me get the next one done correctly.

**Comment by sparkydave1981** [comment]
I just noticed that this plug isn't listed under the AU devices section. Is it too late to get that sorted? (or does it need to be a new PR?)

**Comment by jonathanadams** [comment]
I will sort that for you. No need to open a new pull request.

**Comment by jonathanadams** [comment]
@sparkydave1981 should be working now!

**Pull request merged**
